vim.loader.enable()
require "fray.options"
require "fray.keymaps"
require "fray.plugins"
require "fray.cmp"
require "fray.lsp"
require "fray.telescope"
require "fray.gitsigns"
require "fray.treesitter"
require "fray.autopairs"
require "fray.comment"
require "fray.nvim-tree"
require "fray.bufferline"
require "fray.lualine"
require "fray.toggleterm"
require "fray.indentline"
require "fray.alpha"
require "fray.whichkey"
vim.cmd "colorscheme catppuccin"
